// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLIRgoAkkOEmoznfKl8Yb-TCmACm1X2EQ',
    appId: '1:710097734921:web:b753ef9801b309a53417d8',
    messagingSenderId: '710097734921',
    projectId: 'blogapp-8983e',
    authDomain: 'blogapp-8983e.firebaseapp.com',
    storageBucket: 'blogapp-8983e.appspot.com',
    measurementId: 'G-Y63WHWM385',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgKyPnUhVM2vJS1jETicIBOyo1YcG3zi4',
    appId: '1:710097734921:android:c788bf4cfdd38c203417d8',
    messagingSenderId: '710097734921',
    projectId: 'blogapp-8983e',
    storageBucket: 'blogapp-8983e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA01f6pZPfrI_6WmcikI8KSi4xFwCmM5fI',
    appId: '1:710097734921:ios:00dccc8ecb75c0413417d8',
    messagingSenderId: '710097734921',
    projectId: 'blogapp-8983e',
    storageBucket: 'blogapp-8983e.appspot.com',
    iosBundleId: 'com.example.blogApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA01f6pZPfrI_6WmcikI8KSi4xFwCmM5fI',
    appId: '1:710097734921:ios:4a64d81a33c3724b3417d8',
    messagingSenderId: '710097734921',
    projectId: 'blogapp-8983e',
    storageBucket: 'blogapp-8983e.appspot.com',
    iosBundleId: 'com.example.blogApp.RunnerTests',
  );
}
